version: '2'

services:  

  portainer:
    image: portainer/portainer
    restart: always
    hostname: 'portainer.docker'
    networks:
      - 'gestaoLAN'
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /datadisk/portainer:/data  

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.docker'
    networks:
      - 'CiCdLAN'
    ports:
      - "6022:22"
      - "6080:80"
      - "6443:443"
    volumes:
      - /datadisk/gitlab/data:/var/opt/gitlab
      - /datadisk/gitlab/logs:/var/log/gitlab
      - /datadisk/gitlab/config:/etc/gitlab 
            
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always 
    hostname: 'gitlab.runner.docker'
    networks:
      - 'CiCdLAN'  
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/datadisk/gitlab-runner/config:/etc/gitlab-runner'

  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"    
    volumes:
      - /datadisk/registry:/var/lib/registry    

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    ports:
      - 5080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000

  nexus:
    image: sonatype/nexus3
    volumes:
      - /datadisk/nexus:/nexus-data
    ports:
      - "7080:8081"
  
  


networks:
  CiCdLAN:
    driver: bridge
  gestaoLAN:
    driver: bridge